// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.AzureIntegrationMigration.ApplicationModel.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TraceMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TraceMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.AzureIntegrationMigration.ApplicationModel.Resources.TraceMessages", typeof(TraceMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtering resources by AIS target environment {AzureIntegrationServicesTarget}..
        /// </summary>
        internal static string FilteringResourcesByTarget {
            get {
                return ResourceManager.GetString("FilteringResourcesByTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtering snippet files by deployment environment {DeploymentEnvironment} for snippet {SnippetKey}..
        /// </summary>
        internal static string FilteringSnippetsByEnvironment {
            get {
                return ResourceManager.GetString("FilteringSnippetsByEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtering template files by deployment environment {DeploymentEnvironment} for template {TemplateKey}..
        /// </summary>
        internal static string FilteringTemplatesByEnvironment {
            get {
                return ResourceManager.GetString("FilteringTemplatesByEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found files for deployment environment {DeploymentEnvironment} for template {TemplateKey}..
        /// </summary>
        internal static string FoundFilesForEnvironment {
            get {
                return ResourceManager.GetString("FoundFilesForEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found resource map {ResourceMapKey}..
        /// </summary>
        internal static string FoundResourceMap {
            get {
                return ResourceManager.GetString("FoundResourceMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found snippet {SnippetKey}..
        /// </summary>
        internal static string FoundSnippet {
            get {
                return ResourceManager.GetString("FoundSnippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found file for deployment environment {DeploymentEnvironment} for snippet {SnippetKey}..
        /// </summary>
        internal static string FoundSnippetFileForEnvironment {
            get {
                return ResourceManager.GetString("FoundSnippetFileForEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found snippets for AIS target environment {AzureIntegrationServicesTarget} for resource {ResourceKey}..
        /// </summary>
        internal static string FoundSnippetsForTarget {
            get {
                return ResourceManager.GetString("FoundSnippetsForTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found targets for resource {ResourceKey}..
        /// </summary>
        internal static string FoundTargetsForResource {
            get {
                return ResourceManager.GetString("FoundTargetsForResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found template {TemplateKey}..
        /// </summary>
        internal static string FoundTemplate {
            get {
                return ResourceManager.GetString("FoundTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found templates for AIS target environment {AzureIntegrationServicesTarget} for resource {ResourceKey}..
        /// </summary>
        internal static string FoundTemplatesForTarget {
            get {
                return ResourceManager.GetString("FoundTemplatesForTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading configuration files from {ConfigurationDirectory}..
        /// </summary>
        internal static string LoadingConfigurationFiles {
            get {
                return ResourceManager.GetString("LoadingConfigurationFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading target resources for messaging object {MessagingObjectKey}..
        /// </summary>
        internal static string LoadingTargetResources {
            get {
                return ResourceManager.GetString("LoadingTargetResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading template file {TemplateFile}..
        /// </summary>
        internal static string LoadingTemplateFile {
            get {
                return ResourceManager.GetString("LoadingTemplateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for resource map {ResourceMapKey} in the YAML configuration set..
        /// </summary>
        internal static string LookingForResourceMap {
            get {
                return ResourceManager.GetString("LookingForResourceMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for snippet {SnippetKey} in the YAML configuration set..
        /// </summary>
        internal static string LookingForSnippet {
            get {
                return ResourceManager.GetString("LookingForSnippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for targets for resource {ResourceKey} in the YAML configuration set..
        /// </summary>
        internal static string LookingForTargetsForResource {
            get {
                return ResourceManager.GetString("LookingForTargetsForResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for template {TemplateKey} in the YAML configuration set..
        /// </summary>
        internal static string LookingForTemplate {
            get {
                return ResourceManager.GetString("LookingForTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for templates for resource {ResourceKey}..
        /// </summary>
        internal static string LookingForTemplatesForResource {
            get {
                return ResourceManager.GetString("LookingForTemplatesForResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No snippets found for AIS target environment {AzureIntegrationServicesTarget} for resource {ResourceKey}..
        /// </summary>
        internal static string NoSnippetsForTarget {
            get {
                return ResourceManager.GetString("NoSnippetsForTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No templates found for AIS target environment {AzureIntegrationServicesTarget} for resource {ResourceKey}..
        /// </summary>
        internal static string NoTemplatesForTarget {
            get {
                return ResourceManager.GetString("NoTemplatesForTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendering configuration files in {SourceConfigurationDirectory} and outputting to {TargetConfigurationDirectory}..
        /// </summary>
        internal static string RenderingConfigurationFiles {
            get {
                return ResourceManager.GetString("RenderingConfigurationFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messaging object {MessagingObjectName} of type {MessageObjectType} is not associated with a resource map key..
        /// </summary>
        internal static string ResourceMapKeyNotSpecified {
            get {
                return ResourceManager.GetString("ResourceMapKeyNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving template file {TemplateFile}..
        /// </summary>
        internal static string SavingTemplateFile {
            get {
                return ResourceManager.GetString("SavingTemplateFile", resourceCulture);
            }
        }
    }
}
